### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by j-jsmith** [MaelKubli/RTwitterV2#13]
Hi, your package was recommended to me as it seems to still be working despite Twitter's current change regarding its free access to API. I followed your README.md but keep getting the following error message:

 "Error in data_list[[i]] : 
  attempt to select less than one element in integerOneIndex"

This was my code:

appname <- "XX"
key <- "XX"
secret <- "XX"
access_token <- "XX"
access_secret <- "XX"
bearer_token <- "XX"

test <- get_timelines_v2(token = bearer_token, user_id = "14273050", n = 100)

Do you know why this might be the case?

**Comment by MaelKubli** [comment]
Hello 

I will have a look into this error in the coming days. 
One Question what type of API Access do you have (Academic / Basic)?
This might help me when testing. 

All the best,
Maël

**Comment by j-jsmith** [comment]
HiI‘m using the Academic access. A student I know has an account and we were sharing it since we could no longer apply for it and it worked with other Twitter packages up until February 9th, I asked him for the access token, access secret and bearer token and it doesn‘t work, maybe refreshing them could help?Best, JosephineSent from my iPhoneOn 3 Mar 2023, at 14:46, Maël Kubli ***@***.***> wrote:﻿
Hello
I will have a look into this error in the coming days.
One Question what type of API Access do you have (Academic / Basic)?
This might help me when testing.
All the best,
Maël

**Comment by MaelKubli** [comment]
Hi Again 

I checked the endpoint and for me it is working with the example, you submitted. 
Maybe check if your token is still valid and working. 

It might also be that your code did not work due to malfunctions on Twitter side. 

All the best,
Maël
